language: java
sudo: required

services:
- docker
git:
  depth: 1

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - cp settings.xml $HOME/.m2/settings.xml
  - rm -rf $HOME/.m2/repository/org/teiid/komodo*

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.defaultLogLevel=error -Pimage -Dfabric8.mode=kubernetes

before_script:
  
script: mvn test -B -V -q 

after_success:
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then
      echo "pushing to image to docker";
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push teiid/komodo-server:latest ;
    fi

  - if [[ "$TRAVIS_BRANCH" =~ ^[0-9]+(\.[0-9]+){2} ]]; then
      echo "pushing to image to docker";
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push teiid/komodo-server:$TRAVIS_BRANCH ; 
      docker tag teiid/komodo-server:$TRAVIS_BRANCH teiid/komodo:$(echo $TRAVIS_BRANCH | sed -e 's/\.[0-9][0-9]*$//') ;
      docker push teiid/komodo-server:$(echo $TRAVIS_BRANCH | sed -e 's/\.[0-9][0-9]*$//') ;
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ada7bbc05b2a99cff40
    on_success: change
    on_failure: always
    on_start: never
